spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
  datasource:
    url: jdbc:h2:mem:currency
    username: sa
    password: password
    driverClassName: org.h2.Driver
    data: classpath:data-transactional.sql
  sql:
    init:
      data-locations: classpath:data-transactional.sql
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate.ddl-auto: update
    defer-datasource-initialization: true
    show-sql: false
    properties:
      hibernate:
        globally_quoted_identifiers: true


